# Ãœbung 3.5: Update-Strategie
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlled-deployment
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: controlled
  template:
    metadata:
      labels:
        app: controlled
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
